theme: jekyll-theme-minimal
title: Yasemin Girgin
description: PhD student at Boston University
body {
  font-family: 'Roboto', sans-serif;
  color: #333;
  margin: 0;
  padding: 0;
  background-color: #f5f5f5;
}

h2, h3 {
  font-family: 'Merriweather', serif;
  margin-top: 20px;
}

section {
  padding: 20px;
  max-width: 800px;
  margin: auto;
}

a {
  color: #3498db;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}
